/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import room from '../assets/room/room_compressed.glb';
import { useInterfaceContext } from '../components/Interface';
import { toast } from 'react-toastify';


type GLTFResult = GLTF & {
    nodes: {
        FEUILLE: THREE.Mesh;
        Circle001: THREE.Mesh;
        Test: THREE.Mesh;
        tIGE: THREE.Mesh;
        tIGE003: THREE.Mesh;
        FEUILLE003: THREE.Mesh;
        ['G-cactus_gasteria_1']: THREE.Mesh;
        Glass: THREE.Mesh;
        Image: THREE.Mesh;
        base: THREE.Mesh;
        base002: THREE.Mesh;
        screen: THREE.Mesh;
        Cube032_1: THREE.Mesh;
        Cube032_2: THREE.Mesh;
        suport: THREE.Mesh;
        Cylinder002: THREE.Mesh;
        Cylinder002_1: THREE.Mesh;
        Housing: THREE.Mesh;
        Base: THREE.Mesh;
        Feet: THREE.Mesh;
        Keyboard: THREE.Mesh;
        Screen: THREE.Mesh;
        Ipad_002: THREE.Mesh;
        Ipad_: THREE.Mesh;
        Cylinder014: THREE.Mesh;
        Plane038: THREE.Mesh;
        Plane039: THREE.Mesh;
        BezierCurve001: THREE.Mesh;
        Cube028: THREE.Mesh;
        Cube029: THREE.Mesh;
        Cube032: THREE.Mesh;
        Cube036: THREE.Mesh;
        Cylinder005: THREE.Mesh;
        Cylinder008: THREE.Mesh;
        Cylinder011: THREE.Mesh;
        Cylinder012: THREE.Mesh;
        Cylinder013: THREE.Mesh;
        Cylinder015: THREE.Mesh;
        Cylinder020: THREE.Mesh;
        Cylinder017: THREE.Mesh;
        Cylinder016: THREE.Mesh;
        Plane033: THREE.Mesh;
        Cylinder019: THREE.Mesh;
        Cylinder022: THREE.Mesh;
        Cylinder023: THREE.Mesh;
        Plane: THREE.Mesh;
        Cube002: THREE.Mesh;
        Cube: THREE.Mesh;
        Cube001: THREE.Mesh;
        Cube003: THREE.Mesh;
        Cube004: THREE.Mesh;
        Cube005: THREE.Mesh;
        Cube006: THREE.Mesh;
        Cube014: THREE.Mesh;
        Cube009: THREE.Mesh;
        Cube007: THREE.Mesh;
        Cube008: THREE.Mesh;
        Cube018: THREE.Mesh;
        Cube012: THREE.Mesh;
        Cube010: THREE.Mesh;
        Cube013: THREE.Mesh;
        Cube022: THREE.Mesh;
        Cube016: THREE.Mesh;
        Cube015: THREE.Mesh;
        Cube017: THREE.Mesh;
        Cube026: THREE.Mesh;
        Cube020: THREE.Mesh;
        Cube019: THREE.Mesh;
        Cube021: THREE.Mesh;
        Cube037: THREE.Mesh;
        Cube024: THREE.Mesh;
        Cube023: THREE.Mesh;
        Cube025: THREE.Mesh;
        Succulent_plant: THREE.Mesh;
        Plane021: THREE.Mesh;
        Circle002: THREE.Mesh;
        Plane024: THREE.Mesh;
        Plane004: THREE.Mesh;
        Plane027: THREE.Mesh;
        Plane006: THREE.Mesh;
        Plane030: THREE.Mesh;
        Plane008: THREE.Mesh;
        Plane010: THREE.Mesh;
        Plane012: THREE.Mesh;
        Plane014: THREE.Mesh;
        Plane016: THREE.Mesh;
        Plane018: THREE.Mesh;
        Plane020: THREE.Mesh;
        Plane023: THREE.Mesh;
        Plane026: THREE.Mesh;
        Plane029: THREE.Mesh;
        Plane001: THREE.Mesh;
        Plane002: THREE.Mesh;
        Plane003: THREE.Mesh;
        Plane005: THREE.Mesh;
        Plane007: THREE.Mesh;
        Plane009: THREE.Mesh;
        Plane011: THREE.Mesh;
        Plane013: THREE.Mesh;
        Plane015: THREE.Mesh;
        Plane017: THREE.Mesh;
        Plane019: THREE.Mesh;
        Plane022: THREE.Mesh;
        Plane025: THREE.Mesh;
        Plane028: THREE.Mesh;
        Plane031: THREE.Mesh;
        Cube011: THREE.Mesh;
        MUG002: THREE.Mesh;
        Circle: THREE.Mesh;
        Ikea_SKÅDIS: THREE.Mesh;
        bottom_back_stand000: THREE.Mesh;
        bottom_back_stand001: THREE.Mesh;
        screw_head000: THREE.Mesh;
        screw000: THREE.Mesh;
        screw_head001: THREE.Mesh;
        screw001: THREE.Mesh;
        screw_head002: THREE.Mesh;
        screw002: THREE.Mesh;
        screw_head003: THREE.Mesh;
        screw003: THREE.Mesh;
        top_back_stand: THREE.Mesh;
        Cylinder004: THREE.Mesh;
    };
};


export default function Room(props: JSX.IntrinsicElements['group']): JSX.Element {
    const { nodes } = useGLTF(room) as GLTFResult;

    const ref = React.useRef(null);

    const materials = useMemo(() => {
        return {
            White: new THREE.MeshStandardMaterial({ color: '#EDDFEF' }),
            MetallicWhite: new THREE.MeshStandardMaterial({ color: '#EDDFEF', metalness: 0.2, roughness: 0.25 }),
            Green: new THREE.MeshStandardMaterial({ color: '#6B8F71' }),
            Brown: new THREE.MeshStandardMaterial({ color: '#43291F' }),
            Purple: new THREE.MeshStandardMaterial({ color: '#9381FF' }),
            Black: new THREE.MeshStandardMaterial({ color: '#2E2E34' }),
            MetallicBlack: new THREE.MeshStandardMaterial({ color: '#2E2E34', metalness: 0.3, roughness: 0.35 }),
        };
    }, [ nodes ]);

    return (
        <group ref={ref} {...props} dispose={null}>
            <group name="Scene">
                <group name="Modular_plant" position={[ 1.01, 0.26, -1.03 ]} scale={0.31}>
                    <group name="BezierCurve" position={[ 0, 0.63, 0 ]} scale={0.15} />
                    <group
                        name="BezierCurve003"
                        position={[ 0.06, 0.6, -0.03 ]}
                        rotation={[ -Math.PI, 0.92, -Math.PI ]}
                        scale={0.15}
                    />
                    <mesh
                        name="FEUILLE"
                        castShadow
                        receiveShadow
                        geometry={nodes.FEUILLE.geometry}
                        material={materials.Green}
                        position={[ 0, 0.63, 0 ]}
                        scale={0.15}
                    />
                    <mesh
                        name="Circle001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Circle001.geometry}
                        material={materials.Brown}
                        position={[ 0, 0.6, 0 ]}
                        scale={[ 0.3, 0.68, 0.3 ]}
                    />
                    <mesh
                        name="Test"
                        castShadow
                        receiveShadow
                        geometry={nodes.Test.geometry}
                        material={materials.White}
                        scale={0.15}
                    />
                    <mesh
                        name="tIGE"
                        castShadow
                        receiveShadow
                        geometry={nodes.tIGE.geometry}
                        material={materials.Green}
                        position={[ 0, 0.63, 0 ]}
                        scale={0.15}
                    />
                    <mesh
                        name="tIGE003"
                        castShadow
                        receiveShadow
                        geometry={nodes.tIGE003.geometry}
                        material={materials.Green}
                        position={[ 0.06, 0.6, -0.03 ]}
                        rotation={[ -Math.PI, 0.92, -Math.PI ]}
                        scale={0.15}
                    />
                    <mesh
                        name="FEUILLE003"
                        castShadow
                        receiveShadow
                        geometry={nodes.FEUILLE003.geometry}
                        material={materials.Green}
                        position={[ 0.06, 0.6, -0.03 ]}
                        rotation={[ -Math.PI, 0.92, -Math.PI ]}
                        scale={0.15}
                    />
                </group>
                <group
                    name="Succulent_Plant"
                    position={[ -1.14, 1.39, 1.14 ]}
                    scale={1.96}
                >
                    <mesh
                        name="G-cactus_gasteria_1"
                        castShadow
                        receiveShadow
                        geometry={nodes['G-cactus_gasteria_1'].geometry}
                        material={materials.White}
                        position={[ 0, 0, 0.03 ]}
                    />
                </group>
                <group
                    name="Dell_monitor_24_inch_S2421HN"
                    position={[ -1.15, 1.01, -0.29 ]}
                    rotation={[ 0, Math.PI / 2, 0 ]}
                    scale={1.13}
                >
                    <mesh
                        name="base"
                        castShadow
                        receiveShadow
                        geometry={nodes.base.geometry}
                        material={materials.Purple}
                        position={[ 0, 0.01, 0 ]}
                    />
                    <mesh
                        name="base002"
                        castShadow
                        receiveShadow
                        geometry={nodes.base002.geometry}
                        material={materials.Purple}
                        position={[ 0, 0.06, 0 ]}
                    />
                    <mesh
                        name="screen"
                        receiveShadow
                        geometry={nodes.screen.geometry}
                        material={materials.MetallicBlack}
                        position={[ 0, 0.27, -0.1 ]}
                    />
                    <group name="Bezel" position={[ 0, 0.27, -0.11 ]}>
                        <mesh
                            name="Cube032_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube032_1.geometry}
                            material={materials.Purple}
                        />
                        <mesh
                            name="Cube032_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube032_2.geometry}
                            material={materials.Purple}
                        />
                    </group>
                    <mesh
                        name="suport"
                        castShadow
                        receiveShadow
                        geometry={nodes.suport.geometry}
                        material={materials.Purple}
                        position={[ 0, 0.24, -0.3 ]}
                    />
                    <group name="Stand" position={[ 0, 0.18, 0 ]}>
                        <mesh
                            name="Cylinder002"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder002.geometry}
                            material={materials.Purple}
                        />
                        <mesh
                            name="Cylinder002_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder002_1.geometry}
                            material={materials.Purple}
                        />
                    </group>
                    <mesh
                        name="Housing"
                        castShadow
                        receiveShadow
                        geometry={nodes.Housing.geometry}
                        material={materials.Purple}
                        position={[ 0, 0.27, 0 ]}
                    />
                </group>
                <group
                    name="Lenovo_Legion_Laptop"
                    position={[ -0.88, 1.01, -0.28 ]}
                    rotation={[ 0, Math.PI / 2, 0 ]}
                    scale={0.23}
                >
                    <mesh
                        name="Base"
                        geometry={nodes.Base.geometry}
                        material={materials.Purple}
                        position={[ 0, 0.04, 0.06 ]}
                        rotation={[ 0, -1.57, 0 ]}
                        scale={4.85}
                    />
                    <mesh
                        name="Keyboard"
                        geometry={nodes.Keyboard.geometry}
                        material={materials.Purple}
                        position={[ -0.02, 0.08, 0.02 ]}
                        rotation={[ 0, -1.57, 0 ]}
                        scale={[ 5.34, 4.85, 5.34 ]}
                    />
                    <mesh
                        name="Screen"
                        castShadow
                        geometry={nodes.Screen.geometry}
                        material={materials.Purple}
                        position={[ 0, 0.11, -0.43 ]}
                        rotation={[ -1.69, -Math.PI / 2, 0 ]}
                        scale={4.85}
                    />
                </group>
                <group
                    name="Apple_iPad_With_Keyboard"
                    position={[ -0.83, 1.01, -0.9 ]}
                    rotation={[ 0, 0.66, 0 ]}
                    scale={0.22}
                >
                    <mesh
                        onClick={(): void => {
                            toast.warn(<span className="text-sm font-medium">Hey! Are you trying to steal my stuff?</span>, {
                                position: 'top-right',
                                icon: '🚨',
                                autoClose: 2000,
                                hideProgressBar: true,
                                closeOnClick: true,
                                pauseOnHover: false,
                                theme: 'light',
                            });
                        }}
                        receiveShadow
                        name="Ipad_002"
                        geometry={nodes.Ipad_002.geometry}
                        material={materials.Purple}
                        position={[ 0, 0.01, 0 ]}
                        scale={4.58}
                    >
                        <group name="Empty001" rotation={[ -0.55, 0, 0 ]}>
                            <mesh
                                name="Ipad_"
                                receiveShadow
                                geometry={nodes.Ipad_.geometry}
                                material={materials.MetallicBlack}
                            />
                        </group>
                    </mesh>
                </group>
                <group
                    name="Audio_thecnica"
                    position={[ 0.04, 1.01, -1.04 ]}
                    scale={1.15}
                >
                    <mesh
                        name="BezierCurve001"
                        geometry={nodes.BezierCurve001.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cube028"
                        geometry={nodes.Cube028.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cube029"
                        geometry={nodes.Cube029.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cube032"
                        geometry={nodes.Cube032.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cube036"
                        geometry={nodes.Cube036.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder005"
                        geometry={nodes.Cylinder005.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder008"
                        geometry={nodes.Cylinder008.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        onClick={(): void => {
                            toast.warn(<span className="text-sm font-medium">Beethoven's Symphony No. 7 in A</span>, {
                                position: 'top-right',
                                icon: '🎵',
                                autoClose: 2000,
                                hideProgressBar: true,
                                closeOnClick: true,
                                pauseOnHover: false,
                                theme: 'light',
                            });
                        }}
                        name="Cylinder011"
                        geometry={nodes.Cylinder011.geometry}
                        material={materials.MetallicBlack}
                    />
                    <mesh
                        name="Cylinder012"
                        geometry={nodes.Cylinder012.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder013"
                        geometry={nodes.Cylinder013.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder015"
                        geometry={nodes.Cylinder015.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder020"
                        geometry={nodes.Cylinder020.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder017"
                        geometry={nodes.Cylinder017.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder016"
                        geometry={nodes.Cylinder016.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        castShadow
                        name="Plane033"
                        geometry={nodes.Plane033.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder019"
                        geometry={nodes.Cylinder019.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder022"
                        geometry={nodes.Cylinder022.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Cylinder023"
                        geometry={nodes.Cylinder023.geometry}
                        material={materials.Purple}
                    />
                    <mesh
                        name="Plane"
                        geometry={nodes.Plane.geometry}
                        material={materials.Purple}
                    />
                </group>
                <mesh
                    name="Cube002"
                    geometry={nodes.Cube002.geometry}
                    material={materials.White}
                    position={[ 0, 0.2, 0 ]}
                    scale={[ 1, 1, 1.06 ]}
                />
                <mesh
                    name="Cube"
                    geometry={nodes.Cube.geometry}
                    material={materials.White}
                />
                <mesh
                    name="Cube001"
                    receiveShadow
                    geometry={nodes.Cube001.geometry}
                    material={materials.White}
                />
                <mesh
                    name="Cube003"
                    receiveShadow
                    geometry={nodes.Cube003.geometry}
                    material={materials.White}
                    position={[ 0, 0, 0.49 ]}
                    scale={[ 1, 1.02, 0.78 ]}
                />
                <mesh
                    name="Cube004"
                    castShadow
                    geometry={nodes.Cube004.geometry}
                    material={materials.White}
                    position={[ -0.96, -0.24, -0.22 ]}
                    scale={[ 0.77, 0.69, 1.2 ]}
                />
                <mesh
                    name="Cube005"
                    castShadow
                    geometry={nodes.Cube005.geometry}
                    material={materials.White}
                    position={[ -0.94, -0.28, -0.43 ]}
                    scale={[ 0.81, 0.72, 1.85 ]}
                />
                <mesh
                    name="Cube006"
                    castShadow
                    geometry={nodes.Cube006.geometry}
                    material={materials.White}
                    position={[ 0.08, -0.28, -1.05 ]}
                    rotation={[ 0, Math.PI / 2, 0 ]}
                    scale={[ 0.6, 0.72, 1.26 ]}
                />
                <mesh
                    name="Cube014"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube014.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 1.02, 1.23 ]}
                    rotation={[ -2.85, 1.56, 2.83 ]}
                    scale={[ 1.76, 1.43, 1.43 ]}
                />
                <mesh
                    name="Cube009"
                    geometry={nodes.Cube009.geometry}
                    material={materials.Purple}
                    position={[ -0.99, 1.04, 0.68 ]}
                    rotation={[ -2.96, 1.56, 2.83 ]}
                    scale={[ 1.79, 1.46, 1.46 ]}
                />
                <mesh
                    name="Cube007"
                    geometry={nodes.Cube007.geometry}
                    material={materials.White}
                    position={[ 0.01, -0.24, -1.05 ]}
                    rotation={[ 0, Math.PI / 2, 0 ]}
                    scale={[ 0.59, 0.69, 1.2 ]}
                />
                <mesh
                    name="Cube008"
                    receiveShadow
                    castShadow
                    geometry={nodes.Cube008.geometry}
                    material={materials.White}
                    position={[ -1.06, 0.86, 0.94 ]}
                    scale={[ 0.24, 0.48, 0.39 ]}
                />
                <mesh
                    name="Cube018"
                    geometry={nodes.Cube018.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 1.01, 0.95 ]}
                    rotation={[ -2.7, 1.56, 2.83 ]}
                    scale={[ 1.15, 1.16, 1.16 ]}
                />
                <mesh
                    name="Cube012"
                    geometry={nodes.Cube012.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 1.02, 0.83 ]}
                    rotation={[ -2.85, 1.56, 2.83 ]}
                    scale={[ 1.62, 1.32, 1.32 ]}
                />
                <mesh
                    name="Cube010"
                    geometry={nodes.Cube010.geometry}
                    material={materials.Purple}
                    position={[ -0.99, 1.04, 0.75 ]}
                    rotation={[ -2.94, 1.56, 2.83 ]}
                    scale={[ 1.79, 1.46, 1.46 ]}
                />
                <mesh
                    name="Cube013"
                    geometry={nodes.Cube013.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 1.02, 1.3 ]}
                    rotation={[ -2.85, 1.56, 2.83 ]}
                    scale={[ 1.76, 1.43, 1.43 ]}
                />
                <mesh
                    name="Cube022"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube022.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 0.51, 0.71 ]}
                    rotation={[ -1.26, 1.56, 2.83 ]}
                    scale={[ 0.9, 1.32, 1.32 ]}
                />
                <mesh
                    name="Cube016"
                    geometry={nodes.Cube016.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 1.02, 1.08 ]}
                    rotation={[ -2.84, 1.56, 2.83 ]}
                    scale={[ 1.66, 1.35, 1.35 ]}
                />
                <mesh
                    name="Cube015"
                    geometry={nodes.Cube015.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 1.02, 1.15 ]}
                    rotation={[ -2.75, 1.56, 2.83 ]}
                    scale={[ 1.76, 1.43, 1.43 ]}
                />
                <mesh
                    name="Cube017"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube017.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 1.02, 1.01 ]}
                    rotation={[ -2.84, 1.56, 2.83 ]}
                    scale={[ 1.61, 1.31, 1.31 ]}
                />
                <mesh
                    name="Cube026"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube026.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 0.52, 1.09 ]}
                    rotation={[ -2.75, 1.56, 2.83 ]}
                    scale={[ 1.1, 1.43, 1.43 ]}
                />
                <mesh
                    name="Cube020"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube020.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 0.4, 0.72 ]}
                    rotation={[ -1.26, 1.56, 2.83 ]}
                    scale={[ 1.79, 1.46, 1.46 ]}
                />
                <mesh
                    name="Cube019"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube019.geometry}
                    material={materials.Purple}
                    position={[ -0.99, 1.02, 0.88 ]}
                    rotation={[ -2.83, 1.56, 2.83 ]}
                    scale={[ 1.15, 1.28, 1.29 ]}
                />
                <mesh
                    name="Cube021"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube021.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 0.47, 0.72 ]}
                    rotation={[ -1.26, 1.56, 2.83 ]}
                    scale={[ 1.43, 1.46, 1.46 ]}
                />
                <mesh
                    name="Cube037"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube037.geometry}
                    material={materials.White}
                    position={[ 0.01, 0, 0 ]}
                />
                <mesh
                    name="Cube024"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube024.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 0.52, 1.23 ]}
                    rotation={[ -2.85, 1.56, 2.83 ]}
                    scale={[ 1.76, 1.43, 1.43 ]}
                />
                <mesh
                    name="Cube023"
                    geometry={nodes.Cube023.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 0.52, 1.15 ]}
                    rotation={[ -2.75, 1.56, 2.83 ]}
                    scale={[ 1.76, 1.43, 1.43 ]}
                />
                <mesh
                    name="Cube025"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube025.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 0.52, 1.3 ]}
                    rotation={[ -2.85, 1.56, 2.83 ]}
                    scale={[ 1.76, 1.43, 1.43 ]}
                />
                <mesh
                    name="Succulent_plant"
                    castShadow
                    receiveShadow
                    geometry={nodes.Succulent_plant.geometry}
                    material={materials.Purple}
                    position={[ 0.55, 1, -1.22 ]}
                    scale={0.09}
                >
                    <group name="center" position={[ 0.01, 1.1, 0.07 ]} scale={1.21} />
                    <mesh
                        name="Plane021"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane021.geometry}
                        material={materials.Green}
                        position={[ 0.59, 0.92, -0.13 ]}
                        rotation={[ -Math.PI, 1.44, -Math.PI ]}
                        scale={0.63}
                    />
                    <mesh
                        name="Circle002"
                        castShadow
                        receiveShadow
                        geometry={nodes.Circle002.geometry}
                        material={materials.Brown}
                        position={[ 0, 0.94, 0 ]}
                    />
                    <mesh
                        name="Plane024"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane024.geometry}
                        material={materials.Green}
                        position={[ -0.89, 0.91, 0.14 ]}
                        rotation={[ 0, -1.01, 0 ]}
                        scale={0.46}
                    />
                    <mesh
                        name="Plane004"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane004.geometry}
                        material={materials.Green}
                        position={[ 0.07, 0.92, -0.46 ]}
                        rotation={[ Math.PI, -0.09, Math.PI ]}
                        scale={0.7}
                    />
                    <mesh
                        name="Plane027"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane027.geometry}
                        material={materials.Green}
                        position={[ 0.77, 0.92, -0.41 ]}
                        rotation={[ -Math.PI, 1.05, -Math.PI ]}
                        scale={0.49}
                    />
                    <mesh
                        name="Plane006"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane006.geometry}
                        material={materials.Green}
                        position={[ 0.45, 0.92, 0.26 ]}
                        rotation={[ 0, 0.99, 0 ]}
                        scale={0.7}
                    />
                    <mesh
                        name="Plane030"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane030.geometry}
                        material={materials.Green}
                        position={[ 0.24, 0.91, 0.77 ]}
                        rotation={[ 0, 0.24, 0 ]}
                        scale={0.39}
                    />
                    <mesh
                        name="Plane008"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane008.geometry}
                        material={materials.Green}
                        position={[ -0.04, 0.92, 0.01 ]}
                        rotation={[ 0, -1, 0 ]}
                        scale={[ 0.42, 0.7, 0.42 ]}
                    />
                    <mesh
                        name="Plane010"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane010.geometry}
                        material={materials.Green}
                        position={[ 0.19, 1.06, 0.04 ]}
                        rotation={[ 0, 1.11, 0 ]}
                        scale={[ 0.34, 0.56, 0.34 ]}
                    />
                    <mesh
                        name="Plane012"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane012.geometry}
                        material={materials.Green}
                        position={[ -0.62, 0.91, -0.06 ]}
                        rotation={[ 0, -1.47, 0 ]}
                        scale={0.64}
                    />
                    <mesh
                        name="Plane014"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane014.geometry}
                        material={materials.Green}
                        position={[ 0.78, 0.92, -0.05 ]}
                        rotation={[ 0, 1.55, 0 ]}
                        scale={0.65}
                    />
                    <mesh
                        name="Plane016"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane016.geometry}
                        material={materials.Green}
                        position={[ 0.39, 0.9, -0.73 ]}
                        rotation={[ -Math.PI, 0.65, -Math.PI ]}
                        scale={0.47}
                    />
                    <mesh
                        name="Plane018"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane018.geometry}
                        material={materials.Green}
                        position={[ -0.35, 0.92, 0.62 ]}
                        rotation={[ 0, -0.25, 0 ]}
                        scale={0.7}
                    />
                    <mesh
                        name="Plane020"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane020.geometry}
                        material={materials.Green}
                        position={[ 0.43, 0.94, 0.57 ]}
                        rotation={[ 0, 0.6, 0 ]}
                        scale={0.63}
                    />
                    <mesh
                        name="Plane023"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane023.geometry}
                        material={materials.Green}
                        position={[ -0.8, 0.92, -0.17 ]}
                        rotation={[ Math.PI, -1.21, Math.PI ]}
                        scale={0.59}
                    />
                    <mesh
                        name="Plane026"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane026.geometry}
                        material={materials.Green}
                        position={[ -0.39, 0.96, -0.7 ]}
                        rotation={[ -3.13, -0.67, -3.09 ]}
                        scale={0.44}
                    />
                    <mesh
                        name="Plane029"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane029.geometry}
                        material={materials.Green}
                        position={[ -0.06, 0.92, 0.77 ]}
                        rotation={[ 0, -0.13, 0 ]}
                        scale={0.47}
                    />
                    <mesh
                        name="Plane001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane001.geometry}
                        material={materials.Green}
                        position={[ 0.06, 0.92, 0.22 ]}
                        scale={0.7}
                    />
                    <mesh
                        name="Plane002"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane002.geometry}
                        material={materials.Green}
                        position={[ 0.29, 0.92, -0.13 ]}
                        rotation={[ -Math.PI, 1, -Math.PI ]}
                        scale={0.7}
                    />
                    <mesh
                        name="Plane003"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane003.geometry}
                        material={materials.Green}
                        position={[ -0.19, 0.92, -0.11 ]}
                        rotation={[ Math.PI, -0.81, Math.PI ]}
                        scale={0.7}
                    />
                    <mesh
                        name="Plane005"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane005.geometry}
                        material={materials.Green}
                        position={[ 0.5, 0.92, -0.48 ]}
                        rotation={[ -Math.PI, 0.83, -Math.PI ]}
                        scale={0.55}
                    />
                    <mesh
                        name="Plane007"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane007.geometry}
                        material={materials.Green}
                        position={[ -0.3, 0.92, 0.28 ]}
                        rotation={[ 0, -0.87, 0 ]}
                        scale={0.7}
                    />
                    <mesh
                        name="Plane009"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane009.geometry}
                        material={materials.Green}
                        position={[ 0.07, 0.92, -0.09 ]}
                        rotation={[ Math.PI, -0.08, Math.PI ]}
                        scale={[ 0.42, 0.7, 0.42 ]}
                    />
                    <mesh
                        name="Plane011"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane011.geometry}
                        material={materials.Green}
                        position={[ -0.36, 0.92, -0.46 ]}
                        rotation={[ Math.PI, -1.03, Math.PI ]}
                        scale={0.62}
                    />
                    <mesh
                        name="Plane013"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane013.geometry}
                        material={materials.Green}
                        position={[ -0.13, 0.91, -0.74 ]}
                        rotation={[ 3.14, -0.29, -3.11 ]}
                        scale={0.57}
                    />
                    <mesh
                        name="Plane015"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane015.geometry}
                        material={materials.Green}
                        position={[ 0.09, 0.92, 0.58 ]}
                        rotation={[ 0, 0.06, 0 ]}
                        scale={0.7}
                    />
                    <mesh
                        name="Plane017"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane017.geometry}
                        material={materials.Green}
                        position={[ -0.6, 0.89, -0.46 ]}
                        rotation={[ Math.PI, -1.27, Math.PI ]}
                        scale={0.53}
                    />
                    <mesh
                        name="Plane019"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane019.geometry}
                        material={materials.Green}
                        position={[ -0.58, 0.91, 0.29 ]}
                        rotation={[ 0, -1.12, 0 ]}
                        scale={0.63}
                    />
                    <mesh
                        name="Plane022"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane022.geometry}
                        material={materials.Green}
                        position={[ 0.2, 0.92, -0.68 ]}
                        rotation={[ -Math.PI, 0.26, -Math.PI ]}
                        scale={0.54}
                    />
                    <mesh
                        name="Plane025"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane025.geometry}
                        material={materials.Green}
                        position={[ -0.63, 0.92, 0.54 ]}
                        rotation={[ 0, -0.65, 0 ]}
                        scale={0.5}
                    />
                    <mesh
                        name="Plane028"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane028.geometry}
                        material={materials.Green}
                        position={[ 0.81, 0.92, 0.3 ]}
                        rotation={[ 0, 0.85, 0 ]}
                        scale={0.56}
                    />
                    <mesh
                        name="Plane031"
                        castShadow
                        receiveShadow
                        geometry={nodes.Plane031.geometry}
                        material={materials.Green}
                        position={[ 0.08, 0.9, -0.85 ]}
                        rotation={[ -Math.PI, 0.08, -Math.PI ]}
                        scale={0.41}
                    />
                </mesh>
                <mesh
                    name="Cube011"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube011.geometry}
                    material={materials.Purple}
                    position={[ -0.98, 1.04, 0.6 ]}
                    rotation={[ -2.98, 1.56, 2.83 ]}
                    scale={[ 1.79, 1.46, 1.46 ]}
                />
                <mesh
                    name="MUG002"
                    castShadow
                    receiveShadow
                    geometry={nodes.MUG002.geometry}
                    material={materials.Purple}
                    position={[ -0.9, 1.01, 0.17 ]}
                    rotation={[ 0, 0.79, 0 ]}
                    scale={1.12}
                >
                    <mesh
                        onClick={(): void => {
                            toast.warn(<span className="text-sm font-medium">Did you poison my coffee?</span>, {
                                icon: '💀',
                                position: 'top-right',
                                autoClose: 2000,
                                hideProgressBar: true,
                                closeOnClick: true,
                                pauseOnHover: false,
                                theme: 'light',
                            });
                        }}
                        name="Circle"
                        castShadow
                        receiveShadow
                        geometry={nodes.Circle.geometry}
                        material={materials.Brown}
                        position={[ 0, 0.07, 0 ]}
                        rotation={[ 0, 0.79, 0 ]}
                    />
                </mesh>
                <mesh
                    name="Ikea_SKÅDIS"
                    castShadow
                    receiveShadow
                    geometry={nodes.Ikea_SKÅDIS.geometry}
                    material={materials.MetallicWhite}
                    position={[ 0.03, 1.72, -1.37 ]}
                    rotation={[ Math.PI / 2, 0, 0 ]}
                >
                    <mesh
                        name="screw_head000"
                        geometry={nodes.screw_head000.geometry}
                        material={materials.MetallicWhite}
                        position={[ -0.24, 0.03, -0.23 ]}
                        rotation={[ -Math.PI / 2, 0, 0.65 ]}
                    >
                        <mesh
                            name="screw000"
                            geometry={nodes.screw000.geometry}
                            material={materials.MetallicWhite}
                            rotation={[ 0, 0, -0.65 ]}
                        />
                    </mesh>
                    <mesh
                        name="screw_head001"
                        geometry={nodes.screw_head001.geometry}
                        material={materials.MetallicWhite}
                        position={[ 0.24, 0.03, -0.23 ]}
                        rotation={[ -Math.PI / 2, 0, -0.71 ]}
                    >
                        <mesh
                            name="screw001"
                            geometry={nodes.screw001.geometry}
                            material={materials.MetallicWhite}
                            rotation={[ 0, 0, -0.65 ]}
                        />
                    </mesh>
                    <mesh
                        name="screw_head002"
                        geometry={nodes.screw_head002.geometry}
                        material={materials.MetallicWhite}
                        position={[ -0.24, 0.03, 0.27 ]}
                        rotation={[ -Math.PI / 2, 0, 0.32 ]}
                    >
                        <mesh
                            name="screw002"
                            geometry={nodes.screw002.geometry}
                            material={materials.MetallicWhite}
                            rotation={[ 0, 0, -0.65 ]}
                        />
                    </mesh>
                    <mesh
                        name="screw_head003"
                        geometry={nodes.screw_head003.geometry}
                        material={materials.MetallicWhite}
                        position={[ 0.24, 0.03, 0.27 ]}
                        rotation={[ -1.56, -0.09, 1.1 ]}
                    >
                        <mesh
                            name="screw003"
                            geometry={nodes.screw003.geometry}
                            material={materials.MetallicWhite}
                            rotation={[ 0, 0, -0.65 ]}
                        />
                    </mesh>
                </mesh>
                <mesh
                    name="Cylinder004"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cylinder004.geometry}
                    material={materials.Purple}
                    position={[ -1.21, 1.39, 0.95 ]}
                    rotation={[ Math.PI, -1.37, Math.PI ]}
                    scale={0.97}
                />
            </group>
        </group>
    );
}

useGLTF.preload(room);
